### ISSUE TITLE
Core functionality milestone

### ISSUE THREAD

**Issue by xnzvl** [xnzvl/Karak#7]
# Tracking Core functionality milestone

This issue will be updated as needed.

## TODOs

- [ ] `Hero` class implementation
- [ ] specific Heroes implementations
  - [ ] Wizard
  - [ ] Warlock
  - [ ] Warrior
  - [ ] Thief
  - [ ] Swordsman
  - [ ] Oracle
- [ ] `Monster` instances *"spawner"*
- [ ] `Game` class
  - [ ] main game loop
  - [ ] initialize game

---

- [ ] tests
  - [ ] `Hero`
  - [ ] `Monster` spawner
